### ISSUE TITLE
normalizeBatch target batch?

### ISSUE THREAD

**Issue by pegahsafa** [MarioniLab/archive-cydar#4]
Is there any way to choose a "target batch" when applying the normalizeBatch function, so as to align landmarks to a particular batch? And is it possible to supply any of the flowStats implementation arguments such as bandwidth for density estimation?
Thanks

**Comment by LTLA** [comment]
Yes, this could definitely be done. I'll see if I can add these features over the coming week.

**Comment by pegahsafa** [comment]
Thank you! One additional suggestion--the ability to choose a subset of markers in the flowSet/matrix to be normalized would save some extra code.

**Comment by LTLA** [comment]
1. You can now specify the target batch via `target`.
2. You can now pass arguments to `flowStats::warpSet` via `...`. 
3. You can now specify the markers of interest via `markers=`.

However, two things to note:

- I haven't tested any of these features (even if they are syntatically valid, or if the package builds!) because _flowWorkspace_ is not installing on my machine - I will need to check why.
- Commits will be to https://github.com/MarioniLab/cydar, this repository is now archived.
